### ISSUE TITLE
Hello World sample

### ISSUE THREAD

**Issue by onassar** [lucidsoftware/sample-lucid-extensions#12]
It'd be helpful if there was a simple Hello World package that could be built for people to get a better understand of the architecture.

**Comment by xcwisc** [comment]
Hey onassar, thanks for your feedback! The [import-page](https://github.com/lucidsoftware/sample-lucid-extensions/tree/main/import-page) package is our hello-world/ boilerplate application that is populated for you if you follow this [getting started guide](https://developer.lucid.co/extension-api/#getting-started) on our documentation. [Here](https://github.com/lucidsoftware/sample-lucid-extensions/tree/main/import-page#folder--file-structure) is a high level walk through about the file structure for the extension. We will make it clear this is the hello-world application in the repo!

**Comment by onassar** [comment]
Got it thanks. Do you have any guides, examples or walkthroughs on a package that is focused on adding a panel to the Images area?

**Comment by xcwisc** [comment]
Yes! I would recommend following [this](https://developer.lucid.co/extension-api/#panel-hello-world) guide. If you replace `location: PanelLocation.RightDock` with `location: PanelLocation.ImageSearchTab` for location. The panel will show up in the image area as a new tab.

**Comment by onassar** [comment]
Gr8 thx!

**Comment by onassar** [comment]
Can't seem to get it to show up in the Images Panel.
Code: https://s3.us-west-2.amazonaws.com/onassar.prod.02/screenshots/Screenshot%202023-08-23%20at%205.28.27%20PM.jpg
Rendered UI: https://s3.us-west-2.amazonaws.com/onassar.prod.02/screenshots/Screenshot%202023-08-23%20at%205.28.49%20PM.jpg

**Comment by xcwisc** [comment]
Hey @onassar, this is the intended behavior for now. Sorry for the miscommunication before. Will you be able to close this issue now?

**Comment by onassar** [comment]
Sure
